# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
 adapter: mysql2
 database: aws_consumer_db
 username: root
 #host: localhost
 password: 
 port: 3306
 pool: 10
