require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IaMsController do

  # This should return the minimal set of attributes required to create a valid
  # Iam. As you add validations to Iam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IaMsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all iams as @iams" do
      iam = Iam.create! valid_attributes
      get :index, {}, valid_session
      assigns(:iams).should eq([iam])
    end
  end

  describe "GET show" do
    it "assigns the requested iam as @iam" do
      iam = Iam.create! valid_attributes
      get :show, {:id => iam.to_param}, valid_session
      assigns(:iam).should eq(iam)
    end
  end

  describe "GET new" do
    it "assigns a new iam as @iam" do
      get :new, {}, valid_session
      assigns(:iam).should be_a_new(Iam)
    end
  end

  describe "GET edit" do
    it "assigns the requested iam as @iam" do
      iam = Iam.create! valid_attributes
      get :edit, {:id => iam.to_param}, valid_session
      assigns(:iam).should eq(iam)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Iam" do
        expect {
          post :create, {:iam => valid_attributes}, valid_session
        }.to change(Iam, :count).by(1)
      end

      it "assigns a newly created iam as @iam" do
        post :create, {:iam => valid_attributes}, valid_session
        assigns(:iam).should be_a(Iam)
        assigns(:iam).should be_persisted
      end

      it "redirects to the created iam" do
        post :create, {:iam => valid_attributes}, valid_session
        response.should redirect_to(Iam.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved iam as @iam" do
        # Trigger the behavior that occurs when invalid params are submitted
        Iam.any_instance.stub(:save).and_return(false)
        post :create, {:iam => { "name" => "invalid value" }}, valid_session
        assigns(:iam).should be_a_new(Iam)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Iam.any_instance.stub(:save).and_return(false)
        post :create, {:iam => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested iam" do
        iam = Iam.create! valid_attributes
        # Assuming there are no other iams in the database, this
        # specifies that the Iam created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Iam.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => iam.to_param, :iam => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested iam as @iam" do
        iam = Iam.create! valid_attributes
        put :update, {:id => iam.to_param, :iam => valid_attributes}, valid_session
        assigns(:iam).should eq(iam)
      end

      it "redirects to the iam" do
        iam = Iam.create! valid_attributes
        put :update, {:id => iam.to_param, :iam => valid_attributes}, valid_session
        response.should redirect_to(iam)
      end
    end

    describe "with invalid params" do
      it "assigns the iam as @iam" do
        iam = Iam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Iam.any_instance.stub(:save).and_return(false)
        put :update, {:id => iam.to_param, :iam => { "name" => "invalid value" }}, valid_session
        assigns(:iam).should eq(iam)
      end

      it "re-renders the 'edit' template" do
        iam = Iam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Iam.any_instance.stub(:save).and_return(false)
        put :update, {:id => iam.to_param, :iam => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested iam" do
      iam = Iam.create! valid_attributes
      expect {
        delete :destroy, {:id => iam.to_param}, valid_session
      }.to change(Iam, :count).by(-1)
    end

    it "redirects to the iams list" do
      iam = Iam.create! valid_attributes
      delete :destroy, {:id => iam.to_param}, valid_session
      response.should redirect_to(iams_url)
    end
  end

end
